version: "2.2"
services:
 web:
  build: .
  image: school_enterprise_cooperation
  volumes:
  - .:/code
 nginx:
  build: ./nginx
  ports:
  - "6446:6446"
  volumes:
   - .:/code
  links:
  - "web:web"
